apiVersion: apps/v1
kind: Deployment
metadata:
  name:  mywebappdeploy
  labels:
    name:  mywebapp
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: mywebapp
    spec:
      containers:
      - image:  koteswarararaosairi/project
        name:  mywebapp
---
