apiVersion: apps/v1
kind: Deployment
metadata:
  name:  mywebappdeploy
  labels:
    name:  mywebapp
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: mywebapp
    spec:
      containers:
      - image:  koteswarararaosairi/project
        name:  mywebapp
 ---
apiVersion: v1
kind: Service
metadata:
  name:  mywebappservice
spec:
  selector:
    app:  Selector Label
  type:   NodePort
  ports:
  - name: mywebapp
    port:  80
    targetPort:  8080
    nodeport: 30736
      
