---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  mykotiwebappdeployment
  labels:
    name:  mykotiwebapp
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name:  mykotiwebapp
    spec:
      containers:
      - image:  ipedrazas/docmock 
        name:  mykotiwebappcontainer
        resources:
          requests:
            cpu: "20m"
            memory: "55M"
        livenessProbe:
          httpGet:
            path: /_status/healthz
            port: 5000
          initialDelaySeconds: 90
          timeoutSeconds: 10
        readinessProbe:
 ---
 apiVersion: v1
 kind: service 
metadata:
  name:  mykotiwebappsvc
spec:
  selector:
    app:  mykotiwebapp
  type:   NodePort
  ports:
  - port:  80
    targetPort:  8080
    nodePort: 30736
...
