 ---
apiVersion: v1
kind: Service
metadata:
  name:  mywebappservice
spec:
  selector:
    app:  Selector Label
  type:   NodePort
  ports:
  - name: mywebapp
    port:  80
    targetPort:  8080
    nodeport: 30736
 ---
